name: Lanista Auto Teambattle

on:
  schedule:
    - cron: '*/10 * * * *'  # kör var 10:e minut
  workflow_dispatch:        # möjliggör manuell start

jobs:
  create_team:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lanista auto-clicker
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py
