name: Lanista Auto Teambattle

on:
  schedule:
    # Kör var 10:e minut mellan 05-23 UTC (06-24 CET normaltid)
    - cron: "*/10 5-23 * * *"
  workflow_dispatch:  # Möjliggör manuell start

jobs:
  run-teambattle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run Lanista Auto Clicker
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python main.py
